### ISSUE TITLE
支持没有图形界面的Linux吗？

### ISSUE THREAD

**Issue by ZachL1** [silverling/xdwlan-login#2]
支持没有图形界面的Linux吗？
 
服务器平时都ssh用，不插显示器。但是一旦重启了，就得插显示器、鼠标键盘手动联网登录，极其麻烦。不知道这个是否能不依赖图形界面自动登录？

**Comment by silverling** [comment]
理论上是可以的。等待假期结束后，我添加一下对 Linux 系统的支持。

**Comment by ZachL1** [comment]
感谢开源！

**Comment by silverling** [comment]
你好，现已支持 Linux 系统。可在 [Release](https://github.com/silverling/xdwlan-login/releases) 处下载并解压运行。或者通过下面的安装脚本一键安装（推荐）
```bash
curl -sSL https://github.com/silverling/xdwlan-login/raw/refs/heads/main/scripts/install.sh | bash
```

PS：该程序依赖 Chromium-based 浏览器，<ins>**安装脚本会自动帮你通过包管理器安装 Chromium**</ins>，如果手动从 Release 处下载，则需要手动安装浏览器。在安装脚本中，该程序将被自动安装到 `/usr/local/bin/xdwlan-login`。

安装完成后，请新建文件 `~/.config/xdwlan-login/config.yaml`，并填入以下内容:
```yaml
username: <学号>
password: <密码>
```
然后运行 `xdwlan-login --oneshot` 即可登录校园网。

也可以不加 `--oneshot` 参数，直接执行  `xdwlan-login`，让其以守护进程的方式运行，以实现自动登录和断网重连。
如果你熟悉 _systemd_，可以使用 _systemd_ 的服务管理功能来管理 `xdwlan-login` 的运行。

如果使用过程中遇到问题，请在 Issues 中反馈，谢谢!
